site_name: Code en Stock
nav:
  - Home: index.md
  - Python: python.md
  - JavaScript:
      - AlpineJS: js/alpinejs.md
      - Vue3 Composition Api: js/vue3.md
  - Laravel: laravel.md
  - .NET Core:
      - Razor: dotnet/razor.md
  - Git:
      - gitignore:
          - laravel + vue3: git/gitignore/laravelvue.md
      - Authentification Git: git/auth.md
      - CheatSheet: git/git.md
  - Docker: docker.md
theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
