site_name: Code en Stock
site_description: Tous nos codes, cheatsheets et astuces en tout genre sont garanties sans gluten ! Nos Geeks sont élevés en liberté, et nourris avec du code 100% naturel, sans colorants ni conservateurs ! (Nous vous informons qu'aucun Geek n'a été maltraité ou enlevé à son milieu naturel durant le developpement de ce site)
site_author: HeRrKrUgEr
nav:
  - Accueil: index.md
  - Docker: docker.md
  - DOTNET Core:
      - Razor: dotnet/razor.md
  - Git:
      - gitignore:
          - Projet Laravel et Vue3: git/gitignore/laravelvue.md
      - Authentification Git: git/auth.md
      - CheatSheet: git/git.md
  - Golang:
      - CheatSheet Golang: golang/golang.md
  - Google:
      - Search Engine Tips: google/search.md
  - JavaScript:
      - AlpineJS: js/alpinejs.md
      - Vue3 Composition Api: js/vue3.md
  - Laravel:
      - Laravel Artisan et Eloquent Queries: laravel/laravel.md
      - Laravel Blade: laravel/blade.md
      - Configurer LAMP et déployer une application Laravel sur un VPS: laravel/lamp-vps.md
  - Linux:
      - Commandes Bash Utiles: linux/bash.md
      - GREP: linux/grep.md
      - SED: linux/sed.md
      - SSH: linux/ssh.md
      - Vi-Vim: linux/vim.md

  - Python: python.md
theme:
  name: "material"
  palette:
    scheme: default
    primary: black
  language: "fr"
  logo: images/codeenstock.webp
  highlightjs: true
  color_mode: auto
  custom_dir: overrides
extra:
  analytics:
    provider: google
    property: G-WD04V335CB

markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
