site_name: My Docs
nav:
  - Home: index.md
  - Python: python.md
  - JavaScript: javascript.md
  - Git:
      - Authentification Git: docs/git/auth.md
      - CheatSheet: git.md
  - Docker: docker.git
