site_name: Code en Stock
site_description: Bienvenue sur Code En Stock, tous nos codes, cheatsheets et astuces en tout genre sont garanties sans gluten ! Le premier site quui oeuvre pour la sauvegarde des Geeks de grenier, une éspèce en voie de disparition ! (Nous vous informons qu'aucun Geek n'a été maltraité ou enlevé à son milieu naturel durant le developpement de ce site)
site_author: HeRrKrUgEr
Copyright: A Gauche au Fond du Couloir
nav:
  - Home: index.md
  - Docker: docker.md
  - DOTNET Core:
      - Razor: dotnet/razor.md
  - Git:
      - gitignore:
          - Projet Laravel et Vue3: git/gitignore/laravelvue.md
      - Authentification Git: git/auth.md
      - CheatSheet: git/git.md
  - Google:
      - Search Engine Tips: google/search.md
  - JavaScript:
      - AlpineJS: js/alpinejs.md
      - Vue3 Composition Api: js/vue3.md
  - Laravel: laravel.md
  - Linux:
      - Vi-Vim: vim.md
  - Python: python.md
theme:
  name: "material"
  locale: fr
  highlightjs: true
  color_mode: auto
extra:
  analytics:
    provider: google
    property: G-WD04V335CB
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
